### ISSUE TITLE
Piwk 3.0 cannot "catch" the update links in dashboard

### ISSUE THREAD

**Issue by Glisse1** [piwik/piwik#11169]
I am on piwik 3.0. I have in dashboard the "update to 3.0.1"

- If i move mouse over the box the box with please update link and changelog appears, but it is impossible to click them. The css is wrong, as soon as you move the mouse 1 pixel the box below disappears, before reaching it with the cursor and keeping it open.

- if i click the button itself  the dashboard disappears but nothing happens.

This cat/mouse running after the update might frustrate some. I know that one can also update withing the settings area, but still thought this should be addressed as it is easily fixable in css. Also, why the click on the update button itself does nothing, well, that might be an issue as well.

**Comment by RMastop** [comment]
This is fixed in the 3.0.1 version. If you move the mousepointer real quick, you can update.

**Comment by mattab** [comment]
Unfortunately this is not fixed yet. See: #11111 - we will fix it in next release
