### ISSUE TITLE
Problem with token authentication

### ISSUE THREAD

**Issue by dalaius** [piwik/piwik#11312]
Piwik Version 3.0.0

Hi! Since updating to 3.0.0 we are receiving errors with the api token authentication.

The token url:
http://piwik.ourdomain.at/index.php?module=Widgetize&segment=pageUrl==http://link_to_some_page/&action=iframe&columns[]=nb_visits&moduleToWidgetize=VisitsSummary&actionToWidgetize=getEvolutionGraph&idSite=34&period=week&date=today&disableLink=1&widget=1&token_auth=[insert token]

will show this error message:
Fehler: Sie können auf diese Ressource nicht zugreifen, da es mindestens 'view'-Rechte für die Website-ID 34 benötigt.
Anmelden
(Error: You can't access this ressource, you need at least "view" rights for website-ID ...)

The user, whom the token url belongs to, can see this page, so the error is misleading.

**Comment by tsteur** [comment]
> The user, whom the token url belongs to, can see this page, so the error is misleading.

Do you maybe have a screenshot? Where do you see the error? Is is showing the page with data and the error?

**Comment by dalaius** [comment]
We have it integrated in our cms. there's still data, but we get the error message.

![2017-02-02-enterprise cms](https://cloud.githubusercontent.com/assets/25481884/22540919/4a2c6ade-e923-11e6-8904-473537bff3eb.png)

**Comment by sgiehl** [comment]
This should be related to #11055 and was maybe fixed in 3.0.1-b3

**Comment by r4pp3l** [comment]
We're still having this issue with 3.0.1.
I put my observations here: https://github.com/piwik/piwik/pull/11135#issuecomment-273489067

**Comment by mattab** [comment]
@r4pp3l 

* Please try upgrade to our latest beta: http://piwik.org/faq/how-to-update/faq_159/ -- maybe the issue is fixed there? let us know
* if not, as the other ticket is closed, do you mind copying your observation here? I'm assigning it to 3.0.2 already but we look forward to your confirmation.

**Comment by mattab** [comment]
Still cannot reproduce this even when not logged in... @r4pp3l @dalaius any chance you could email us a URL where we can see this bug in action, using latest 3.0.2 beta?

**Comment by mattab** [comment]
we can be contacted at: http://piwik.org/contact/

**Comment by r4pp3l** [comment]
@mattab Here is a paste of my observations from jan 19 (ticket #11135)

Our piwik installation updated from 2.17.0 to 3.0.1 on the weekend.

Since this update our users can no longer use the widgetized dashboard with the same error described here.

Is it possible that this problem is not yet completely fixed?

See the following screens:
This has the module=Live Request opened. I don't see the token_auth being "forwarded" here in any form.

![1](https://cloud.githubusercontent.com/assets/9200121/23145469/b8e76910-f7ce-11e6-9d0b-5c170d8b3068.png)


This has the method=API.getWidgetMetadata Request opened. There's a valid "token_auth" under form data (post). So here it this seems to work


![2](https://cloud.githubusercontent.com/assets/9200121/23145473/bf0a413c-f7ce-11e6-9f0e-61654f803545.png)


Is it possible that is problem was regarded as solved because the "test user" was logged in into the backend anyway? Because in that case the token_auth doesn't seem to matter and the dashboard's widget would therefore work nevertheless.

**Comment by r4pp3l** [comment]
In addition to that. I updated out piwik installation from 3.0.01 to 3.0.2b4. The Problem still exists. I will send you an url to a widget example via the aforementioned contact form in a moment.

Thanks in advance! It would be greatly appreciated if you could fix the issue. Maybe even in 3.0.2 ;) We have lots of people complaining.

**Comment by tsteur** [comment]
Looking at the URL the problem is that you are using the Dashboard module directly instead of going through the Widgetize module.

The URL needs to look like this: http://demo.piwik.org/index.php?module=Widgetize&action=iframe&moduleToWidgetize=Dashboard&actionToWidgetize=index&idSite=3&period=week&date=yesterday

**Comment by r4pp3l** [comment]
Thanks a lot!
