### ISSUE TITLE
Piwik Error : RssRenderer.php(47): Warning - simplexml_load_string()

### ISSUE THREAD

**Issue by abolfazl-ziaratban** [piwik/piwik#11346]
i install piwik and after login , i get this errors :

```
WARNING: .../plugins/RssWidget/RssRenderer.php(47): Warning - simplexml_load_string(): ^ - Piwik 3.0.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING: .../plugins/RssWidget/RssRenderer.php(47): Warning - simplexml_load_string(): &amp;quot; marginheight=&amp;quot;0&amp;quot; frameborder=&amp;quot;0&amp;quot; vspace=&amp;quot;0&amp;quot; hspace=&amp;quot;0&amp;quot;&amp;gt;&amp;lt;/iframe&amp;gt;&amp;lt;/body&amp;gt;&amp;lt;/html&amp;gt; - Piwik 3.0.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING: .../plugins/RssWidget/RssRenderer.php(47): Warning - simplexml_load_string(): Entity: line 2: parser error : Premature end of data in tag html line 1 - Piwik 3.0.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING: .../plugins/RssWidget/RssRenderer.php(47): Warning - simplexml_load_string(): &amp;quot; marginheight=&amp;quot;0&amp;quot; frameborder=&amp;quot;0&amp;quot; vspace=&amp;quot;0&amp;quot; hspace=&amp;quot;0&amp;quot;&amp;gt;&amp;lt;/iframe&amp;gt;&amp;lt;/body&amp;gt;&amp;lt;/html&amp;gt; - Piwik 3.0.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING: .../plugins/RssWidget/RssRenderer.php(47): Warning - simplexml_load_string(): ^ - Piwik 3.0.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING: .../plugins/RssWidget/RssRenderer.php(47): Warning - simplexml_load_string(): Entity: line 2: parser error : Opening and ending tag mismatch: head line 1 and html - Piwik 3.0.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING: .../plugins/RssWidget/RssRenderer.php(47): Warning - simplexml_load_string(): ^ - Piwik 3.0.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING: .../plugins/RssWidget/RssRenderer.php(47): Warning - simplexml_load_string(): &amp;lt;/title&amp;gt;&amp;lt;/head&amp;gt;&amp;lt;body&amp;gt;&amp;lt;iframe src=&amp;quot;http://10.10.34.34?type=Invalid Site&amp;amp;policy=Ma - Piwik 3.0.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING: .../plugins/RssWidget/RssRenderer.php(47): Warning - simplexml_load_string(): ^ - Piwik 3.0.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING: .../plugins/RssWidget/RssRenderer.php(47): Warning - simplexml_load_string(): Entity: line 2: parser error : EntityRef: expecting ';' - Piwik 3.0.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING: .../plugins/RssWidget/RssRenderer.php(47): Warning - simplexml_load_string(): &amp;lt;/title&amp;gt;&amp;lt;/head&amp;gt;&amp;lt;body&amp;gt;&amp;lt;iframe src=&amp;quot;http://10.10.34.34?type=Invalid Site&amp;amp;policy=Ma - Piwik 3.0.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING: .../plugins/RssWidget/RssRenderer.php(47): Warning - simplexml_load_string(): Entity: line 2: parser error : Opening and ending tag mismatch: meta line 1 and head - Piwik 3.0.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
```

**Comment by tsteur** [comment]
It looks like the document / feed you receive is misformed.

Which PHP version is that on? I presume you installed Piwik 3.0.1? It may work if you remove the "Piwik blog" widget from your dashboard. 

In case you are familiar with PHP, you could debug what feed content you get by temporarily replacing

```php
$rss = simplexml_load_string($content);
```

with

```php
return htmlentities($content);
$rss = simplexml_load_string($content);
``` 

and then replacing the blog widget in your Piwik dashboard

**Comment by abolfazl-ziaratban** [comment]
yes i installed piwik 3.0.1 .
i disabled **RssWidget** plugin and my problem is solved.

**Comment by tsteur** [comment]
OK thank you for letting us know. The actual problem persists but likely related to server configuration.
