### ISSUE TITLE
Testcookie causes warning in browser console

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#17829]
related to https://github.com/matomo-org/matomo/pull/17744
reported in https://forum.matomo.org/t/javascript-error-trying-to-set-test-cookie-pk-testcookie-domain/42655

Since Matomo 4.4.0, setting the testcookie seems to cause this error to be logged in the browser console:

> There was an error setting cookie `_pk_testcookie_domain`. Please check domain and path.

**Comment by meibegger** [comment]
I just updated to 4.4.0 and get a similar Error:

In our container cookies are disabled, but when i use a private/icognito browser window i get
`There was an error setting cookie `_pk_id.X.XXXX`. Please check domain and path.`

**Comment by mtoensing** [comment]
Same here. I see the same error like @meibegger

**Comment by howdytom** [comment]
This error message shows up on all Matomo installations running v4.4

**Comment by Findus23** [comment]
@mtoensing, @howdytom This has been fixed with #17830, which will be released in 4.4.1. If you want to test the fix, you can already install the release candidate for it.

**Comment by mamorg79** [comment]
Hi there,

I updated to release 4.4.1 when it was first available. But this issue is still there. So what would you recommend to do?
Could you reopen this?

**Comment by sgiehl** [comment]
@mamorg79 Is it exact that warning? Are you maybe using the tag manager? If so maybe you need to release a new container version. Otherwise did you clear the browser cache to ensure it's not a caching issue?

**Comment by mamorg79** [comment]
> @mamorg79 Is it exact that warning? Are you maybe using the tag manager? If so maybe you need to release a new container version. Otherwise did you clear the browser cache to ensure it's not a caching issue?

Sorry for the inconvenience, some of my developers published an old script and there was an mistake placed in it.

**Comment by Nyaundi** [comment]
I have a similar error. How can I solve it

**Comment by ValenDigital** [comment]
We have multiple sites that show this exact same issue on inconito and private browsers. Running the latest 4.13.0 self hosted version. How can we get this fixed?
