### ISSUE TITLE
Report generated info missing since Matomo 4.6.x 

### ISSUE THREAD

**Issue by tomper00** [piwik/piwik#18476]
The "report generated" info is not visible anymore after Matomo 4.6.x

I can see that the info is still in the code like this:
`<h2 class="card-title ng-isolate-scope" report-generated="Report generated 12&nbsp;min&nbsp;5s ago" piwik-enriched-headline="" data-v-app="">`

But I am not able to display it somehow.

**Comment by sgiehl** [comment]
@diosmosis might that be Vue related?

**Comment by diosmosis** [comment]
@sgiehl yes, fixed here: https://github.com/matomo-org/matomo/pull/18478

**Comment by justinvelluppillai** [comment]
Actually in #18035 we removed the report generated icon and moved the report generated info to the other info icon. You can see screenshots in #17815.

Will close this issue and the PR.

**Comment by tomper00** [comment]
After updating to 4.6.2 today the icon is still missing so the information about "Report generated" is still missing. 
<img width="1224" alt="icon missing" src="https://user-images.githubusercontent.com/366013/145850922-6c1a6dad-d850-47a3-8edf-2d5f458814ae.png">

**Comment by justinvelluppillai** [comment]
The icon is removed and the Report generated time is shown where you indicated.

<img width="674" alt="Screen Shot 2021-12-14 at 7 19 33 AM" src="https://user-images.githubusercontent.com/1127121/145866866-b239eb5d-e4ac-4b47-a7b5-8654178ba510.png">

**Comment by peterhashair** [comment]
It seems like the helper footer text is missing. Going to make a PR for that.
