### ISSUE TITLE
DataTables w/ empty rows are rendered incorrectly when in DataTable Maps w/ other datatables

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#6206]
DataTable\Map indexing sites like:

```
"1" => array(
    array( // first and only row
        'nb_visits' => 1
    )
),
"2" => array(
    array() // no rows
)
```

renders to: `{"1": 1, "2": []}`

**Comment by tsteur** [comment]
What is the expected output?

**Comment by tsteur** [comment]
FYI: to reproduce I am using this code in an API.php

```
    public function test()
    {
        $map = new DataTable\Map();
        $table = DataTable::makeFromSimpleArray(array('nb_visits' => '1'));
        $map->addTable($table, '1');
        $map->addTable(new DataTable(), '2');

        return $map;
    }
```

**Comment by diosmosis** [comment]
Does it do that w/o the 'label' column?

**Comment by tsteur** [comment]
I'm not sure what you mean?

**Comment by diosmosis** [comment]
Your example has a 'label' column + the 'nb_visits' one, but the one I posted (a while ago) only has one column ('nb_visits'). That's probably what triggered the bug for me, but can't remember.

**Comment by tsteur** [comment]
Using this code 

```
    public function test()
    {
        $map = new DataTable\Map();

        $row   = new Row(array(Row::COLUMNS => array('nb_visits' => '1')));
        $table = new DataTable();
        $table->addRow($row);
        $map->addTable($table, '1');

        $map->addTable(new DataTable(), '2');

        return $map;
    }
```

results in 

```
{"1":[{"nb_visits":"1"}],"2":[]}
```

and 

```

array (
  1 => 
  array (
    0 => 
    array (
      'label' => 'nb_visits',
      'value' => '1',
    ),
  ),
  2 => 
  array (
  ),
)
```

**Comment by diosmosis** [comment]
Maybe it was fixed, I'll explore when I'm able.

**Comment by tsteur** [comment]
OK. Probably the issue still exist but need the right structure

**Comment by mattab** [comment]
@diosmosis is it something we should care about in 3.0.0? if yes, please move it there

**Comment by diosmosis** [comment]
Can no longer reproduce.
