### ISSUE TITLE
Error with non-installed Piwik

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#7759]
Currently if we download Piwik but don't run the installer, the CLI console will not work. This is because the container doesn't have the config file of the Diagnostics plugin added, so the `DiagnosticService` cannot be created. This is the kind of issues I was trying to avoid in #7175.

I will fix this regression by getting the service lazily in the `diagnostic:run` command. However maybe this Diagnostics plugin should be enabled by default (even in no `config.ini.php` config exists). By the way I have no idea how the installer runs without loading some of the plugins. So the question is how do I make a plugin be loaded by default, even if Piwik is not installed?

**Comment by mnapoli** [comment]
First step done (fixed the console in de925df)

**Comment by mattab** [comment]
> So the question is how do I make a plugin be loaded by default, even if Piwik is not installed?

if you add the plugin to: `$pluginToAlwaysActivate` in Plugin\Manager it should do the trick

**Comment by saleemkce** [comment]
@mnapoli okay great. But my point is, for a user cloning the piwik repository newly, after updating composer with CLI, it should work, right? or plus using command "git pull upstream master", the piwik site should load without issues because it's a fresh clone. But I kept getting PHP-DI class not found error. Okay, let me check it after a few hours because you have made commits and report it to you later.

**Comment by mnapoli** [comment]
@saleemkce could you restore the original `composer.json`, run `composer install` and copy-paste the error message here?

@mattab I've tried this one but it doesn't seem to work. The comment says `These are always activated and cannot be deactivated` so I think it's just that we can't deactivate them, but if I remove my config and run `./console plugin:list` I only see this list:

```
+---------------+-------------------+-----------+
| Plugin        | Core or optional? | Status    |
+---------------+-------------------+-----------+
| Installation  | Core              | Activated |
| SitesManager  | Core              | Activated |
| UsersManager  | Core              | Activated |
| CoreAdminHome | Core              | Activated |
| Login         | Core              | Activated |
+---------------+-------------------+-----------+
```

**Comment by saleemkce** [comment]
@mnapoli  Do you say that "composer.json" from this https://github.com/piwik/piwik/blob/master/composer.json ? Because now I am confused, because before using "git clone ... " I removed my local piwik folder completely + data base after taking backup. So "git clone ..." have provided only the latest composer.json. Am I right?

**Comment by mnapoli** [comment]
@saleemkce yes use the `composer.json` that was downloaded when you did `git clone` (which is the one you linked to)

**Comment by saleemkce** [comment]
@mnapoli okay, as I am away from home and don't have access to local piwik application, I will report it later today. Thanks.

**Comment by saleemkce** [comment]
@mnapoli Awesome, I replaced the composer.json and ran "composer install". My app is now back. The issue is PHP-DI is fixed by your latest commit. Thanks.

**Comment by mnapoli** [comment]
> By the way I have no idea how the installer runs without loading some of the plugins.

Still don't know about that, I'm curious if you have an answer @mattab
