### ISSUE TITLE
piwik.php is returning 400

### ISSUE THREAD

**Issue by opnoack** [piwik/piwik#7850]
I have updated piwik to the latest version a couple days ago. I am monitoring the http return code of the piwik.php file. After the update I receive 400 instead of 200 before. There is no error logged in the webserver since the returncode comes directly from the script.

![piwik](https://cloud.githubusercontent.com/assets/4449536/7491042/cfe46b52-f3e5-11e4-9e5f-1e2933b0bc16.png)

**Comment by luciopileggi** [comment]
Same problem on my installation... The drupal piwik module is broken because of this problem https://www.drupal.org/node/2483815

**Comment by tsteur** [comment]
Yes, since Piwik 2.13.0 we do return a HTTP 400 (Bad request) when requesting `piwik.php` without any parameters since it cannot track anything without any parameters. We missed to document/announce that, I'm very sorry about that. I will add this now.

Can you use eg `piwik.php?rec=0` instead?

I'm wondering for what kind of checks you use piwik.php?

**Comment by tsteur** [comment]
Is this maybe also related to #7810 (Stable page for ELB health check)?

**Comment by opnoack** [comment]
Thanks for your reply. Unfortunately that doesn't solve the problem for me. Still receiving 400 code with parameters.

**Comment by tsteur** [comment]
True, this morning I got a 200 when I tried it but now getting a 400. Weird... What exactly do you want to monitor / check by calling `piwik.php`? Is it a requirement that it is the `piwik.php`? or could it just be any file?

**Comment by opnoack** [comment]
I think it could be any file. We're just monitoring the return code with a monitoring system and since it worked all there time so far there was no need to change it. Is there another way to verify that the piwik installation is working?

**Comment by tsteur** [comment]
@mattab what do we test for in our monitoring? I think we do test for something? 

Also you might be interested in #7810 as well

**Comment by opnoack** [comment]
Well the old behaviour was okay for us, I don't see the point in changing the default return code to 400 for the piwik.php. 

To test the application it must be accessible via http and the application must be able to establish a database connection (and maybe even run a query on the database). The processes for web- and database-server are monitored separately.

**Comment by tsteur** [comment]
> and the application must be able to establish a database connection (and maybe even run a query on the database)

Just FYI: I don't think piwik.php does this when there are no URL parameters but I'm not 100% sure. As another user asked for it in the other issue maybe it actually makes sense to provide an "API" / file for this that tests different kind of things. `index.php` cannot be really used since it might redirect when there is an update to execute. Waiting for feedback of @mattab for now

**Comment by yamlfd** [comment]
Users need to enter the path to their piwik installation. The only way to verify that they entered the correct path is doing a http request and verify that the tracker path is correct. Therefore I have chosen piwik.php  with status code 200 in past. Blocking request to this php file with status 400 is bad idea as this has broken now ~17.000 installations.

I can change this in a future release, but now all current installations are broken.

**Comment by tsteur** [comment]
OK, what I will do for now is to return a HTTP 200 in case a `GET piwik.php` is performed without any query or POST parameters. EG `GET http://example.org/piwik.php` will return a HTTP 200. Is that okay?

Next step would be at some point to actually provide a file or API for this maybe. Waiting for response of @mattab re my previous question. 

I reckon we can close this issue as soon as the PR is merged and discuss everything following in #7810

**Comment by yamlfd** [comment]
The drupal module only makes a GET - no POST. Solution sounds file. Looking forward to a reliable and future safe solution.

**Comment by yamlfd** [comment]
Aside - how soon can we expect a release with this fix included?

**Comment by tsteur** [comment]
I added a test and explained it there to make sure it won't be removed again and explained it there.

I'm not sure how soon we can expect it. Usually we release a new version around the 15th of a month. Possibly this will be the case. @mattab can tell more re this.

**Comment by mattab** [comment]
>  Just FYI: I don't think piwik.php does this when there are no URL parameters but I'm not 100% sure. As another user asked for it in the other issue maybe it actually makes sense to provide an "API" / file for this that tests different kind of things. index.php cannot be really used since it might redirect when there is an update to execute. Waiting for feedback of @mattab for now

Created an issue to discuss  How do I monitor that Piwik service is up? #7904

**Comment by tsteur** [comment]
Why not reuse #7810 ? Or is that something different?

**Comment by babielmri** [comment]
Hello, why is a HEAD-request not allowed?

**Comment by tsteur** [comment]
what do you mean by it's not allowed? I haven't tested it but should work in general?

**Comment by babielmri** [comment]
> OK, what I will do for now is to return a HTTP 200 in case a GET piwik.php is performed without any query or POST parameters. EG GET http://example.org/piwik.php will return a HTTP 200. Is that okay?

So, you have only allowed a GET without any parameters but not a HEAD.

Examples:

> telnet 127.0.0.1 80
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
GET /piwik.php        
<a href='/'>Piwik</a> is a free/libre web <a href='http://piwik.org'>analytics</a> that lets you keep control of your data.Connection closed by foreign host.

> telnet 127.0.0.1 80
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
HEAD /piwik.php
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
Connection closed by foreign host.

**Comment by tsteur** [comment]
OK I get it. The code checks for `GET` specifically. Do you mind creating a new issue for this as this one is already resolved and the HEAD request is a different feature/bug? We should maybe always allow  `HEAD` and `GET` interchangably

**Comment by talus46** [comment]
Just to let you know the issue is still there with the  upgrade to 2.14.1 and is related to database.
The real issue I get is:
 Error query: fetch() failed: Unknown column 'visit_first_action_time' in 'field list' : ...
but the error is masked with http error code 400. 
So or the update didn't update the database schema or there's a typo in the field  name in the code .

**Comment by babielmri** [comment]
A new issue for HEAD-requests and the http-response-code 400 was created: https://github.com/piwik/piwik/issues/8397

**Comment by frictionel** [comment]
With Piwik 2.14.2, using the proxy-script, I saw a lot of "400 Bad Request" today. Which is the second time after 2015-07-14.

The request URLs look legit. First I thought it might be a problem with the database because it had connection problems around the same time but when I rerequest one of the URLs now I still get the error without db connection issues.

Can there be another reason besides missing parameters?

**Comment by tsteur** [comment]
It can have many different reasons. For example if the requested website can't be found (should not be the case here) or if for any other reason there are no logged requests. I'd recommend to create a new issue or to ask in forum
