### ISSUE TITLE
misc/others/api_internal_call.php is broken

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8311]
Reported in forum: http://forum.piwik.org/read.php?2,127892

Error: `Fatal error: Uncaught exception 'Piwik\Container\ContainerDoesNotExistException' with message 'The root container has not been created yet.'`

This error can be found in Piwik demo script - http://demo.piwik.org/misc/others/api_internal_call.php

This script is documented in: https://developer.piwik.org/guides/querying-the-reporting-api (and currently broken, see second half of page)

I found the bug report also on WP forum - https://wordpress.org/support/topic/after-update-to-piwik-2140-no-stats-website-broken.

**Comment by mattab** [comment]
fixed in https://github.com/piwik/piwik/commit/47cf78277659048d55061b1914f940ffe56067f4

**Comment by braekling** [comment]
Hi @mattab - I applied the patch, but now I run into this:

```
Fatal error: Uncaught exception 'Piwik\Container\ContainerDoesNotExistException' with message 'The root container has not been created yet.' in /var/www/vhosts/.../httpdocs/stats/core/Container/StaticContainer.php:40 Stack trace: #0 /var/www/vhosts/.../httpdocs/stats/core/Container/StaticContainer.php(80): Piwik\Container\StaticContainer::getContainer() #1 /var/www/vhosts/.../httpdocs/stats/core/FrontController.php(206): Piwik\Container\StaticContainer::get('path.tmp') #2 /var/www/vhosts/.../httpdocs/wp-content/plugins/wp-piwik/classes/WP_Piwik/Request/Php.php(31): Piwik\FrontController->init() #3 /var/www/vhosts/.../httpdocs/wp-content/plugins/wp-piwik/classes/WP_Piwik/Request/Php.php(14): WP_Piwik\Request\Php->call('method=VisitsSu...', 'http://www.brae...', 'module=API&form...') #4 /var/www/vhosts/.../httpdocs/wp-content/plugins/wp-piwik/classes/WP_Piwik/Request.php(63): WP_Piwik\Request\Php->request('method=VisitsSu...') #5 /var/www/vhosts/.../httpdocs/wp- in /var/www/vhosts/.../httpdocs/stats/core/Container/StaticContainer.php on line 40

Fatal error: Uncaught exception 'Piwik\Container\ContainerDoesNotExistException' with message 'The root container has not been created yet.' in /var/www/vhosts/.../httpdocs/stats/core/Container/StaticContainer.php:40 Stack trace: #0 /var/www/vhosts/.../httpdocs/stats/core/Container/StaticContainer.php(80): Piwik\Container\StaticContainer::getContainer() #1 /var/www/vhosts/.../httpdocs/stats/core/Config.php(62): Piwik\Container\StaticContainer::get('Piwik\Config') #2 /var/www/vhosts/.../httpdocs/stats/core/Url.php(347): Piwik\Config::getInstance() #3 /var/www/vhosts/.../httpdocs/stats/core/Url.php(67): Piwik\Url::getCurrentHost() #4 /var/www/vhosts/.../httpdocs/stats/core/FrontController.php(87): Piwik\Url::getCurrentUrl() #5 /var/www/vhosts/.../httpdocs/stats/core/FrontController.php(181): Piwik\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array) #6 [internal function]: Piwik\FrontController::triggerSafeModeWhenError() #7 {main} thrown in /var/www/vhosts/.../httpdocs/stats/core/Container/StaticContainer.php on line 40
```

Maybe I miss something? This is how I init the FrontController:

```
if (file_exists(PIWIK_INCLUDE_PATH . "/index.php"))
   require_once PIWIK_INCLUDE_PATH . "/index.php";
if (file_exists(PIWIK_INCLUDE_PATH . "/core/API/Request.php"))
   require_once PIWIK_INCLUDE_PATH . "/core/API/Request.php";
if (class_exists('Piwik\FrontController'))
   \Piwik\FrontController::getInstance()->init();
```

I'm not able to get WP-Piwik working again since Piwik 2.14.0.

**Comment by propertunist** [comment]
i just tested this fix with my problem (api renderer format not valid) and am still seeing the same error in the log:

```
PHP message: Exception #1436824607: exception 'Exception' with message 'Renderer format 'json' not valid. Try any of the following instead: .' in /var/www/piwik/core/API/ApiRenderer.php:123
Stack trace:
#0 /var/www/piwik/core/API/ResponseBuilder.php(40): Piwik\API\ApiRenderer::factory('json', Array)
#1 /var/www/piwik/core/API/Request.php(211): Piwik\API\ResponseBuilder->__construct('json', Array)
#2 /mysite/lib/functions.php(82): Piwik\API\Request->process()
#3 /mysite/lib/functions.php(89): piwik_get_country_from_ip()
#4 /mysite/menu/site.php(169): get_area_code_from_ip_data()
```

**Comment by mattab** [comment]
@braekling maybe you need to add same two lines as in https://github.com/piwik/piwik/commit/47cf78277659048d55061b1914f940ffe56067f4 ?

**Comment by mattab** [comment]
@propertunist what is your problem, the error message seems un-related? what is your script generating this error?

**Comment by propertunist** [comment]
i am referring to this issue, which was marked as a duplicate of #8311:
https://github.com/piwik/piwik/issues/8333

**Comment by mattab** [comment]
@propertunist do you have the script source code used to reproduce this bug?

**Comment by propertunist** [comment]
do you need more than i already provided in the other ticket? e.g.

```
$request = new Request ('
module=API
&method=UserCountry.getLocationFromIP
&ip=' . $current_IP . '
&format=json
&token_auth=' . $piwik_secret
);
```

**Comment by braekling** [comment]
@mattab Adding these lines to my code causes the same issue as reported by @propertunist #8333:

```Fatal error: Uncaught exception 'Exception' with message 'Renderer format 'php' not valid.```

(If I test my current development branch which already uses json, I get the related error message: ```Renderer format 'json' not valid```.)

**Comment by propertunist** [comment]
this issue has not been fixed for me in 2.14.1.
i have run the upgrade and i still see exactly the same fatal errors when running an API call. the 2.14 workaround still changes the fatal error from the 'root container has not been created yet' message to the 'renderer format not valid: 'json'' message. but ultimately the outcome remains - fatal error.

**Comment by mattab** [comment]
@braekling @propertunist the script api_internal_call.php is working now: http://demo.piwik.org/misc/others/api_internal_call.php

please create a new issue for your problem and we will investigate - i'll set it to 2.14.2 milestone (since it looks like we will have another dot release later). thanks

**Comment by mattab** [comment]
in the issue, it would really help if you can write a minimal script that we can use to reproduce your issue

**Comment by propertunist** [comment]
ok, i have provided that info in a new ticket here: https://github.com/piwik/piwik/issues/8365

**Comment by braekling** [comment]
To keep this clear, I added my script excerpt to @propertunist new ticket, too. #8635
