### ISSUE TITLE
Mysql 5.7: The MySQL server is running with the --secure-file-priv option so it cannot execute this statement: LOAD DATA INFILE

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9528]
Mysql 5.7 can return an error during archiving process: `The MySQL server is running with the --secure-file-priv option so it cannot execute this statement: LOAD DATA INFILE`

See more info as provided by @oraclerob in https://github.com/piwik/piwik/issues/9419#issuecomment-171588963

**Comment by theyosh** [comment]
This also happens when you try to install Piwik for the first time. It will give an error during the checks.

The solution I used:
in /etc/mysql/my.cnf add below [mysqld] 

secure-file-priv = ""


More info: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_secure_file_priv

**Comment by mattab** [comment]
@theyosh would you mind trying our latest 2.16.0 beta release? it should fix the issue :+1:

**Comment by theyosh** [comment]
Ok, I have reverted my MySQL config file, so the default value for secure-file-priv is enabled again. The installation check is now OK. No error / warning message about this MySQL setting. So looks good!

Have not tested the logfile import yet. Also archiving is not yet tested.

**Comment by theyosh** [comment]
Problem is still there... I have the following error after installation.

LOAD DATA INFILE
Using LOAD DATA INFILE will greatly speed Piwik's archiving process up. To make it available to Piwik, try updating your PHP & MySQL software and make sure your database user has the FILE privilege.
If your Piwik server tracks high traffic websites (eg. > 100,000 pages per month), we recommend to try fix this problem.
Error: LOAD DATA INFILE failed... Error was:
Try #1: LOAD DATA INFILE : SQLSTATE[HY000]: General error: 1290 The MySQL server is running with the --secure-file-priv option so it cannot execute this statement,
Try #2: LOAD DATA LOCAL INFILE : SQLSTATE[42000]: Syntax error or access violation: 1148 The used command is not allowed with this MySQL version[42000]
Troubleshooting: FAQ on piwik.org

so problem is still there. Not during installation, but when I look at the System check option in the interface

**Comment by dazall** [comment]
Use LOAD DATA local INFILE ...

**Comment by yht** [comment]
I think it's a MySQL issues, not piwik.
I found this, maybe it can help someone.
http://stackoverflow.com/questions/32737478/how-should-i-tackle-secure-file-priv-in-mysql

**Comment by chenzuoli** [comment]
i get this error on windows, how can i do?

**Comment by marcobeierer** [comment]
I just had the same issue and setting `secure-file-priv = ""` works fine, but it's not the best solution from a security point of view. A short quote from the documentation: _If empty, the variable has no effect. This is not a secure setting._

It would be better to set the value as narrow as possible. The following did work for me:
```
[mysqld]
secure-file-priv = "/path/to/matomo/tmp/assets/"
```

**Comment by chenzuoli** [comment]
very thinks , it's ok!

At 2018-08-23 01:53:10, "Marco Beierer" <notifications@github.com> wrote:


I just had the same issue and setting secure-file-priv = "" works fine, but it's not the best solution from a security point of view. A short quote from the documentation: If empty, the variable has no effect. This is not a secure setting.

It would be better to set the value as narrow as possible. The following did work for me:

[mysqld]
secure-file-priv = "/path/to/matomo/tmp/assets/"

**Comment by RaviFefar** [comment]
you can store CSV file another location and MySQL store CSV file this location /var/lib/mysql-files/.

`$ SELECT @@GLOBAL.secure_file_priv;`

More info: https://devnote.in/error-1290-hy000-the-mysql-server-is-running-with-the-secure-file-priv/
